{% set name = "wcslib" %}
{% set version = "5.20" %}
{% set sha256 = "0bc037db498cbd8e17ecaedd72fad15d6810ae885793882d5736f746f64c0fb1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://newton.cx/~peter/files/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - no-x-tests.patch # avoid deluges of pgplot warnings
    - no-Otarget.patch

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - flex
  host:
    - cfitsio
    - pgplot 5.2.*  # [not win]
  run:
    - cfitsio
    - pgplot 5.2.*  # [not win]

test:
  commands:
    # Main validation performed in 'make check' stage
    - test -f $PREFIX/lib/libwcs$SHLIB_EXT

about:
  home: http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/
  license: LGPL
  license_file: COPYING.LESSER
  summary: 'Library for World Coordinate System computations'

extra:
  recipe-maintainers:
    - pkgw
