{% set name = "wcslib" %}
{% set version = "8.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.atnf.csiro.au/people/mcalabre/WCS/{{ name }}-{{ version }}.tar.bz2
  sha256: b666c79568fc0cf16b6d585ff3d560ae5e472c3b1125a90ccc8038f8e84aca19
  patches:
    - no-x-tests.patch  # avoid deluges of pgplot warnings
    - cross-compiling-configure.patch  # [build_platform != target_platform]

build:
  number: 1
  skip: true  # [win]
  run_exports:
    # changes soname at major versions
    # https://abi-laboratory.pro/tracker/timeline/wcslib
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - flex
    - make

  host:
    - cfitsio
    - pgplot 5.2.*  # [not win]
  run:
    - cfitsio
    - pgplot 5.2.*  # [not win]

test:
  commands:
    # Main validation performed in 'make check' stage
    - test -f $PREFIX/lib/libwcs$SHLIB_EXT

about:
  home: http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Library for World Coordinate System computations

extra:
  recipe-maintainers:
    - pkgw
